version: '3.8'

services:
  # Next.js Application (pre-built)
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      # You can change this path to wherever you rsync your files
      # Option 1: Relative path (relative to docker-compose location)
      - ./app-dist:/app
      # Option 2: Absolute path (uncomment and customize)
      # - /data/coolify/applications/chess-app/app-dist:/app
    command: node server.js  # Runs the standalone server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
      # Copy your production env vars here
      - NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL:-wss://ws-chess.rndev.site}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped
    depends_on:
      - websocket
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WebSocket Server (pre-built)
  websocket:
    image: node:20-alpine
    working_dir: /app
    volumes:
      # You can change this path to wherever you rsync your files
      # Option 1: Relative path (relative to docker-compose location)
      - ./ws-dist:/app
      # Option 2: Absolute path (uncomment and customize)
      # - /data/coolify/applications/chess-app/ws-dist:/app
    command: node index.js
    ports:
      - "3001:3001"
      - "3002:3002"  # Health check port
    environment:
      - NODE_ENV=production
      - WS_PORT=3001
      - HEALTH_PORT=3002
      - REDIS_URL=${REDIS_URL}  # Use external Redis URL (e.g., from Coolify-managed Redis)
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://chess.rndev.site}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL:-wss://ws-chess.rndev.site}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge