# Coolify Docker Compose using GitHub Container Registry
# This version pulls pre-built images from GitHub Packages instead of building
version: '3.8'

services:
  # Next.js Application (from GitHub Container Registry)
  app:
    image: ghcr.io/bezalel6/2ban-2chess:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL:-wss://ws-chess.rndev.site}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://chess.rndev.site}
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://chess.rndev.site}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - websocket
    networks:
      - coolify
    labels:
      - coolify.managed=true
      - coolify.port=3000
      - coolify.domain=chess.rndev.site
    restart: unless-stopped

  # WebSocket Server (still build from source for now)
  # You could create a separate image for this if needed
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}  # Use Coolify's managed Redis
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://chess.rndev.site}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://chess.rndev.site}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - coolify
    labels:
      - coolify.managed=true
      - coolify.port=3001
      - coolify.domain=ws-chess.rndev.site
    restart: unless-stopped

networks:
  coolify:
    external: true