services:
  coolify-db:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: coolifypassword
      POSTGRES_DB: coolify
    volumes:
      - coolify-db:/var/lib/postgresql/data
    networks:
      - coolify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coolify"]
      interval: 10s
      timeout: 5s
      retries: 5

  coolify-redis:
    image: redis:alpine
    container_name: coolify-redis
    restart: unless-stopped
    networks:
      - coolify-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  coolify-soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: coolify-soketi
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: "0"
      SOKETI_DEFAULT_APP_ID: coolify
      SOKETI_DEFAULT_APP_KEY: coolify-app-key
      SOKETI_DEFAULT_APP_SECRET: coolify-app-secret
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: "true"
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - coolify-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001"]
      interval: 10s
      timeout: 5s
      retries: 5

  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_healthy
    environment:
      # Application
      APP_ENV: production
      APP_KEY: base64:J4QVGsRJssVFfGD/HQwFEJk3mSEPLs2QaIPwCPrhVhQ=
      APP_DEBUG: false
      APP_URL: http://localhost:8000
      APP_PORT: 8000
      
      # Database
      DB_CONNECTION: pgsql
      DB_HOST: coolify-db
      DB_PORT: 5432
      DB_DATABASE: coolify
      DB_USERNAME: coolify
      DB_PASSWORD: coolifypassword
      
      # Redis
      REDIS_HOST: coolify-redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      
      # Docker
      DOCKER_HOST: unix:///var/run/docker.sock
      
      # Coolify specific
      COOLIFY_INSTANCE_ID: local
      COOLIFY_DEFAULT_LOCALE: en
      HORIZON_ENABLED: true
      SCHEDULER_ENABLED: true
      
      # Pusher/Soketi WebSocket settings
      BROADCAST_DRIVER: pusher
      PUSHER_APP_ID: coolify
      PUSHER_APP_KEY: coolify-app-key
      PUSHER_APP_SECRET: coolify-app-secret
      PUSHER_HOST: coolify-soketi
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      VITE_PUSHER_APP_KEY: coolify-app-key
      VITE_PUSHER_HOST: localhost
      VITE_PUSHER_PORT: 6001
      VITE_PUSHER_SCHEME: http
      PUSHER_HOST_FOR_CLIENTS: localhost
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/www/html/storage/app/public
      - ./ssh-keys:/var/www/html/storage/app/ssh-keys
    ports:
      - "8000:8080"
    networks:
      - coolify-network

networks:
  coolify-network:
    driver: bridge

volumes:
  coolify-db:
    driver: local